import type { Config } from "tailwindcss";

// Design tokens copied 1:1 from the uploaded HTML mockups (landing / upload / results)
// so the rebuilt Next.js pages match pixel-for-pixel.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#4f46e5",
        outline: "#777587",
        surface: "#faf8ff",
        "on-primary-fixed": "#0f0069",
        "on-secondary-fixed": "#002113",
        "on-surface-variant": "#464555",
        background: "#faf8ff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "surface-container-high": "#e2e7ff",
        "surface-container": "#eaedff",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#00714d",
        "tertiary-container": "#534ada",
        "inverse-surface": "#283044",
        primary: "#3525cd",
        "tertiary-fixed-dim": "#c3c0ff",
        "on-primary": "#ffffff",
        "surface-dim": "#d2d9f4",
        error: "#ba1a1a",
        "tertiary-fixed": "#e3dfff",
        "on-secondary": "#ffffff",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#dbd8ff",
        "on-primary-container": "#dad7ff",
        "secondary-fixed": "#6ffbbe",
        tertiary: "#3a2cc1",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#dae2fd",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-fixed": "#100069",
        secondary: "#006c49",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#372abf",
        "inverse-primary": "#c3c0ff",
        "surface-container-low": "#f2f3ff",
        "primary-fixed": "#e2dfff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "gutter-lg": "2rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        margin: "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-sm": "1rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "headline-xl-mobile": ["Sora", "sans-serif"],
        "display-hero": ["Sora", "sans-serif"],
        "mono-code": ["Inter", "monospace"],
        "headline-sm": ["Sora", "sans-serif"],
        "headline-xl": ["Sora", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md-medium": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Sora", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.006em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-hero": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "mono-code": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["15px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.011em", fontWeight: "400" }],
        "label-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md-medium": ["14px", { lineHeight: "22px", letterSpacing: "-0.006em", fontWeight: "500" }],
        "display-hero-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
