"""
FastAPI wrapper around the AutoNotes hybrid pipeline.

Run `python extract_pipeline.py path/to/AutoNotes.ipynb` first (in this
directory) to produce pipeline.py, then:

    pip install -r requirements.txt
    uvicorn app:app --host 0.0.0.0 --port 8000

Set PIPELINE_API_URL=http://localhost:8000 in the Next.js app's .env.local
to point the frontend at this server.
"""

from typing import Literal, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

try:
    import pipeline  # generated by extract_pipeline.py
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "pipeline.py not found. Run `python extract_pipeline.py AutoNotes.ipynb` first."
    ) from exc

app = FastAPI(title="AutoNotes Pipeline API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class GenerateRequest(BaseModel):
    youtube_url: str
    output_language: Literal["english", "hindi"] = "english"
    audio_language: Optional[Literal["en", "hi"]] = None


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/generate")
def generate(req: GenerateRequest):
    """
    Mirrors generate_auto_notes_hybrid(youtube_url, output_language, audio_language)
    from Cell 17 of AutoNotes.ipynb and returns its result dict verbatim —
    the Next.js /api/generate route maps that dict 1:1 onto the results page.
    """
    result = pipeline.generate_auto_notes_hybrid(
        req.youtube_url,
        output_language=req.output_language,
        audio_language=req.audio_language,
    )
    if result is None:
        raise HTTPException(
            status_code=500,
            detail="Pipeline returned no result (download or transcription likely failed — check server logs).",
        )
    return result
